export const SAVED_JSON_FETCH_IN_PROGRESS = 'SAVED_JSON_FETCH_IN_PROGRESS';
export const SAVED_JSON_FETCH_SUCCESS = 'SAVED_JSON_FETCH_SUCCESS';
export const SAVED_JSON_FETCH_ERROR = 'SAVED_JSON_FETCH_ERROR';
