export const SAVED_JSON_FETCH_IN_PROGRESS = 'SAVED_JSON_FETCH_IN_PROGRESS';
export const SAVED_JSON_FETCH_SUCCESS = 'SAVED_JSON_FETCH_SUCCESS';
export const SAVED_JSON_FETCH_ERROR = 'SAVED_JSON_FETCH_ERROR';

export const EDITED_JSON_LOAD = 'EDITED_JSON_LOAD';
export const EDITED_JSON_CHANGE = 'EDITED_JSON_CHANGE';
