export const SAVED_JSON_FETCH_IN_PROGRESS = 'SAVED_JSON_FETCH_IN_PROGRESS';
export const SAVED_JSON_FETCH_SUCCESS = 'SAVED_JSON_FETCH_SUCCESS';
export const SAVED_JSON_FETCH_ERROR = 'SAVED_JSON_FETCH_ERROR';

export const EDITED_JSON_LOAD = 'EDITED_JSON_LOAD';
export const EDITED_JSON_CHANGE = 'EDITED_JSON_CHANGE';
export const EDITED_JSON_DELETE = 'EDITED_JSON_DELETE';

export const VIEW_MODAL_OPEN = 'VIEW_MODAL_OPEN';
export const VIEW_MODAL_CLOSE = 'VIEW_MODAL_CLOSE';

export const JSON_CLEAR = 'JSON_CLEAR';
